---

- name: pull customs-server docker image
  become: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-customs-server
    tag: "{{ customs_docker_tag }}"
  register: image

- debug: var=image

- name: Start customs-server docker container
  become: true
  docker_container:
    name: customs
    image: mozilla/fxa-customs-server{{ ':' + customs_docker_tag }}
    state: "{{ customs_docker_state }}"
    network_mode: host
    ports:
      - 7000:7000
    command: node bin/customs_server.js
    env:
      ALLOWED_PHONE_NUMBERS: "19164400029"
      NODE_ENV: "stage"
      IP_ADDRESS: "0.0.0.0"
      MAX_ACCOUNT_ACCESS: "1000"
      MAX_ACCOUNT_STATUS_CHECK: "1000"
      UID_RATE_LIMIT: "1000"
      BANS_REGION: "us-west-2"
      BANS_QUEUE_URL: "{{ customs_ban_queue_url }}"
  register: container

- debug: var=container

- meta: flush_handlers
