---

- name: install human tools
  become: true
  yum:
    name: "{{ item }}"
    state: present
    use_backend: yum
  with_items:
    - emacs-nox
    - strace
    - lsof
    - tmux
    - htop
    - mysql

- name: get team public keys
  git: repo=https://github.com/mozilla/identity-pubkeys.git
       dest=/data/identity-pubkeys
       version=9e0bba655d8ba6b7d32cbb246814f1c4cde6156e
       force=true
  notify: update authorized_keys
