---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
auth_public_url: "{{ public_protocol }}://{{ domain_name }}/auth"
oauth_domain_name: "oauth-{{ domain_name }}"
oauth_public_url: "{{ public_protocol }}://{{ oauth_domain_name }}"
profile_public_url: "{{ public_protocol }}://{{ domain_name }}/profile"
sync_tokenserver_url: "{{ public_protocol }}://{{ domain_name }}/syncserver/token"
content_public_url: "{{ public_protocol }}://{{ domain_name }}"
content_static_resource_url: "{{ public_protocol }}://{{ domain_name }}"
content_public_port: 80
content_private_port: 3030
content_git_repo: https://github.com/mozilla/fxa-content-server.git
content_git_version: master
content_docker_tag: latest
content_docker_state: started
