---
public_protocol: https
private_protocol: http
domain_name: "{{ subdomain }}.{{ hosted_zone }}"
auth_public_url: "{{ public_protocol }}://{{ domain_name }}/auth"
oauth_domain_name: "oauth-{{ domain_name }}"
oauth_public_url: "{{ public_protocol }}://{{ oauth_domain_name }}"
profile_public_url: "{{ public_protocol }}://{{ domain_name }}/profile"
sync_tokenserver_url: "{{ public_protocol }}://{{ domain_name }}/syncserver/token"
content_public_url: "{{ public_protocol }}://{{ domain_name }}"
content_static_resource_url: "{{ public_protocol }}://{{ domain_name }}"
content_public_port: 80
content_private_port: 3030
content_git_repo: https://github.com/mozilla/fxa-content-server.git
content_docker_tag: latest
content_docker_state: started
# N.B. the leading newline on the value below is important,
# it prevents ansible from parsing it as a python dict.
content_scoped_keys_validation: >-

  {
    "https://identity.mozilla.com/apps/oldsync": {
      "redirectUris": [
        "fxaclient://android.redirect",
        "https://lockbox.firefox.com/fxa/ios-redirect.html",
        "https://lockbox.firefox.com/fxa/android-redirect.html",
        "https://accounts.firefox.com/oauth/success/3c49430b43dfba77",
        "https://latest.dev.lcip.org/oauth/success/3c49430b43dfba77",
        "https://stable.dev.lcip.org/oauth/success/3c49430b43dfba77"
      ]
    },
    "https://identity.mozilla.com/apps/lockbox": {
       "redirectUris": [
         "https://2aa95473a5115d5f3deb36bb6875cf76f05e4c4d.extensions.allizom.org/",
         "https://mozilla-lockbox.github.io/fxa/ios-redirect.html",
         "https://lockbox.firefox.com/fxa/ios-redirect.html",
         "https://lockbox.firefox.com/fxa/android-redirect.html"
       ]
     },
     "https://identity.mozilla.com/apps/notes": {
       "redirectUris": [
         "https://dee85c67bd72f3de1f0a0fb62a8fe9b9b1a166d7.extensions.allizom.org/",
         "https://mozilla.github.io/notes/fxa/android-redirect.html"
       ]
     },
     "https://identity.mozilla.com/apps/send": {
       "redirectUris": [
         "https://send2.dev.lcip.org/api/fxa/oauth"
       ]
     },
     "https://identity.mozilla.com/admin": {
       "redirectUris": [
         "fxaclient://fenix.redirect"
       ]
     }
  }
