---

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_basket_proxy.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_basket_proxy.conf
  notify: reload nginx config

- name: create shared mount point for configuration info
  file: path=/data/config/basket state=directory owner=app group=app mode=0777
  sudo: true

- name: configure fxa-basket-proxy
  sudo: true
  sudo_user: app
  template: src=config.json.j2 dest=/data/config/basket/local.json

- name: pull basket docker image
  sudo: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-basket-proxy
    tag: "{{ basket_proxy_docker_tag }}"
  register: image

- debug: var=image

- name: Start basket-proxy server docker container
  sudo: true
  docker_container:
    name: basket-proxy
    image: mozilla/fxa-basket-proxy{{ ':' + basket_proxy_docker_tag }}
    state: started
    network_mode: host
    ports:
      - 1114:1114
    command: node bin/basket-proxy-server.js
    env:
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/basket:/config
  register: container

- debug: var=container

- name: Start basket-event-handler docker container
  sudo: true
  docker_container:
    name: basket-event-handler
    image: mozilla/fxa-basket-proxy{{ ':' + basket_proxy_docker_tag }}
    state: started
    network_mode: host
    command: node bin/basket-event-handler.js
    env:
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/basket:/config
  register: container

- debug: var=container

- name: Start basket-fake docker container
  sudo: true
  docker_container:
    name: basket-fake
    image: mozilla/fxa-basket-proxy{{ ':' + basket_proxy_docker_tag }}
    state: started
    network_mode: host
    ports:
      - 10140:10140
    command: node bin/fake-basket-server.js
    env:
      CONFIG_FILES: "/config/local.json"
    volumes:
      - /data/config/basket:/config
  register: container

- debug: var=container

- meta: flush_handlers
