---

- name: configure nginx upstream
  sudo: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_content.conf
  notify: reload nginx config

- name: configure nginx location
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_content.conf
  notify: reload nginx config

- name: pull content-server docker image
  sudo: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-content-server
    tag: "{{ content_docker_tag }}"
  register: image

- debug: var=image

- name: Start content-server docker container
  sudo: true
  docker_container:
    name: content
    image: mozilla/fxa-content-server{{ ':' + content_docker_tag }}
    state: started
    ports:
      - 3030:3030
    command: node server/bin/fxa-content-server.js
    env:
      NODE_ENV: "production"
      CONFIG_FILES: "/app/server/config/production.json"
      HOST: "0.0.0.0"
      EXPERIMENTS_ENABLE_POLLING: 'false'
      EXPERIMENTS_GIT_REPO: ""
      EXPERIMENTS_STORAGE_DIR: "/tmp"
      FXA_URL: "{{ auth_public_url }}"
      PUBLIC_URL: "{{ content_public_url }}"
      FXA_OAUTH_URL: "{{ oauth_public_url }}"
      FXA_PROFILE_URL: "{{ profile_public_url }}"
      SYNC_TOKENSERVER_URL: "{{ sync_tokenserver_url }}"
      FXA_MARKETING_EMAIL_API_URL: "{{ content_public_url }}/basket"
      FXA_MARKETING_EMAIL_PREFERENCES_URL: "https://www-dev.allizom.org/newsletter/existing/"
  register: container

- debug: var=container

- meta: flush_handlers
