---

- name: configure nginx upstream
  become: true
  template: src=upstream.conf.j2 dest=/etc/nginx/conf.d/upstream/http_fxa_content.conf
  notify: reload nginx config

- name: configure nginx location
  become: true
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/location/http_fxa_content.conf
  notify: reload nginx config

- name: pull content-server docker image
  become: true
  docker_image:
    # pull image always. In a pending update to ansible, it will only set
    # changed:true if the image has actually changed. However, docker_container
    # `state:started` will only re-start if image of configuration has
    # changed.
    force: true
    state: present
    name: mozilla/fxa-content-server
    tag: "{{ content_docker_tag }}"
  register: image

- debug: var=image

- name: Start content-server docker container
  become: true
  docker_container:
    # See note in https://github.com/mozilla/fxa-dev/tree/docker#about-using-docker_container-and-quoting-of-environment-values
    name: content
    image: mozilla/fxa-content-server{{ ':' + content_docker_tag }}
    state: "{{ content_docker_state }}"
    ports:
      - 3030:3030
    command: node server/bin/fxa-content-server.js
    env:
      NODE_ENV: "production"
      CONFIG_FILES: "/app/server/config/production.json"
      HOST: "0.0.0.0"
      NEW_SETTINGS: "true"
      FXA_URL: "{{ auth_public_url }}"
      PUBLIC_URL: "{{ content_public_url }}"
      FXA_OAUTH_URL: "{{ oauth_public_url }}"
      FXA_PROFILE_URL: "{{ profile_public_url }}"
      SYNC_TOKENSERVER_URL: "{{ sync_tokenserver_url }}"
      #PAIRING_CHANNEL_SERVER_URL: "wss://{{ domain_name }}/channelserver/v1/ws/"
      PAIRING_CHANNEL_SERVER_URL: "wss://dev.channelserver.nonprod.cloudops.mozgcp.net/v1/ws/"
      PAIRING_SERVER_BASE_URI: "wss://dev.channelserver.nonprod.cloudops.mozgcp.net"
      SUBSCRIPTIONS_ENABLED: "true"
      SUBSCRIPTIONS_MANAGEMENT_URL: "https://payments-dev.fxa.nonprod.cloudops.mozgcp.net"
      FXA_MARKETING_EMAIL_PREFERENCES_URL: "https://www-dev.allizom.org/newsletter/existing/"
      SCOPED_KEYS_ENABLED: 'true'
      ANSIBLE_RESTART_FIVE: 'true'
      SCOPED_KEYS_VALIDATION: "{{ content_scoped_keys_validation }}"
      ALLOWED_METRICS_FLOW_ORIGINS: "null,http://localhost:8001,http://localhost:8000,http://localhost:8000,https://www.mozilla.org,https://www.allizom.org,https://www-demo5.allizom.org,https://www-demo4.allizom.org,https://www-demo3.allizom.org,https://www-dev.allizom.org,https://fx-breach-alerts.herokuapp.com,https://monitor-v2.herokuapp.com"
  register: container

- debug: var=container

- meta: flush_handlers
