---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - "environments/{{ stack_name }}.yml"
  vars:
    authdb_primary_host: "127.0.0.1"
    authdb_primary_password: ""
    authdb_replica_host: "127.0.0.1"
    authdb_replica_password: ""
    oauth_db_host: "127.0.0.1"
    oauth_db_password: ""
    profile_db_host: "127.0.0.1"
    profile_db_password: ""
    sync_db_host: "127.0.0.1"
    sync_db_password: ""
  roles:
    - common
    - simplehttp
    - ses
    - memcached
    - mysql
    - customs
    - auth
    - authdb
    - content
    - basket-proxy
    - oauth
    - profile
    - rp
    - rp-untrusted
    - cron_update
    - team
