---

- name: Configure instance
  hosts: localhost
  connection: local
  vars_files:
    - "defaults.yml"
    - "environments/{{ stack_name }}.yml"
  roles:
    - common
    - web
    - mysql
    - ses
    - redis
    - memcached
    - pushbox
    - channelserver
    - customs
    - authdb
    - auth
    - email-service
    - content
    - basket-proxy
    - rp
    - rp-untrusted
    - oauth
    - oauth-console
    - verifier
    - sync
    - profile
    - docker-gc
    - cron_update
    - team
