---

- name: install nginx
  sudo: true
  yum: name=nginx state=present

- name: ensure /etc/nginx/conf.d/upstream directory
  file: path=/etc/nginx/conf.d/upstream state=directory
  sudo: true

- name: ensure /etc/nginx/conf.d/location directory 
  file: path=/etc/nginx/conf.d/location state=directory
  sudo: true

- name: delete nginx default.conf
  sudo: true
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: copy base nginx.conf
  sudo: true
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx config

- name: start nginx
  sudo: true
  service: name=nginx state=started enabled=true
