---

- name: create app user
  sudo: true
  user: name=app state=present append=yes

- name: update installed packages
  sudo: true
  yum: name=* state=latest

- name: install base packages
  sudo: true
  yum: name={{ item }} state=present
  with_items:
    - docker
    - gcc-c++
    - git
    - ntp
    - python-pip

- name: ensure a docker group is created to allow running without sudo
  become: true
  group: name=docker state=present

- name: add ec2-user to the docker group
  become: true
  user: name=ec2-user append=yes groups=docker

- name: install nave
  sudo: true
  get_url: url=https://raw.githubusercontent.com/dannycoates/nave/master/nave.sh
           dest=/usr/bin/nave
           mode=755

- name: install node
  sudo: true
  command: /usr/bin/nave usemain {{ node_version }}
  # TODO detect actual changes
  changed_when: false

- name: install docker-py module
  sudo: true
  yum: enablerepo=epel name=python-docker-py state=present

# for mounting configuration information in subdirectoris under /data/config
# XXX fix mode/ownership
- file: path=/data/config state=directory owner=app group=app mode=0777
  sudo: true

- name: configure ntp
  sudo: true
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: start ntp
  sudo: true
  service: name=ntpd state=started enabled=true

- name: start docker
  become: true
  service: name=docker state=started enabled=true

- meta: flush_handlers
